CREATE TABLE Employee (
	EmployeeId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	DepartmentId INTEGER NOT NULL,
	EmployeeName TEXT NOT NULL,
	SupervisorFlag TEXT NOT NULL,
	FOREIGN KEY (DepartmentId) REFERENCES Department(DepartmentId)
);

CREATE TABLE Department (
	DepartmentId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	DepartmentName TEXT NOT NULL,
	SupervisorId INTEGER NOT NULL,
	ExpenseBudget INTEGER NOT NULL
);

CREATE TABLE TrainingPrograms (
	TrainingId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ProgramName TEXT NOT NULL,
	EmployeeId INTEGER NOT NULL,
	MaxAttendees INTEGER NOT NULL,
	StartDate INTEGER NOT NULL,
	EndDate INTEGER NOT NULL,
	FOREIGN KEY (EmployeeId) REFERENCES Employee(EmployeeId)
);

CREATE TABLE Computers (
	ComputerId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	EmployeeId INTEGER NOT NULL,
	PurchaseDate INTEGER NOT NULL,
	DecomissionDate INTEGER NOT NULL,
	FOREIGN KEY (EmployeeId) REFERENCES Employee(EmployeeId)
);

CREATE TABLE Customers (
	CustomerId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	OrderId INTEGER NOT NULL,
	PaymentTypes TEXT NOT NULL,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	AccountCreationDate INTEGER NOT NULL,
	InactiveFlag TEXT NOT NULL,
	FOREIGN KEY (OrderId) REFERENCES Orders(OrderId)
);

CREATE TABLE Products (
	ProductId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TypeId INTEGER NOT NULL,
	Price INTEGER NOT NULL,
	Title TEXT NOT NULL,
	Description TEXT NOT NULL,
	CustomerId INTEGER NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId),
	FOREIGN KEY (TypeId) REFERENCES ProductTypes(TypeId)
);

CREATE TABLE Orders (
	OrderId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CustomerId INTEGER NOT NULL,
	ProductId INTEGER NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId),
	FOREIGN KEY (ProductId) REFERENCES Products(ProductId)
);

CREATE TABLE ProductTypes (
	TypeId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CategoryName TEXT NOT NULL
);

